# Generated by Django 3.2.9 on 2021-11-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSemanal',
            fields=[
                ('idmenu', models.IntegerField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('idplatillo', models.IntegerField()),
            ],
            options={
                'db_table': 'menu_semanal',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UsuarioGeneral',
        ),
    ]
